import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, readFileSync, writeFileSync, rmSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';
const installer = fileURLToPath(new URL('../scripts/install.ps1', import.meta.url));
test('clean project installation distributes SOPs and installed generator reads them', t => {
  const shell = process.platform === 'win32' ? 'powershell.exe' : 'pwsh';
  if (spawnSync(shell, ['-NoProfile', '-Command', '$PSVersionTable.PSVersion.ToString()']).error?.code === 'ENOENT') return t.skip('PowerShell unavailable');
  const root = mkdtempSync(join(tmpdir(), 'buyna-install-sop-'));
  t.after(() => rmSync(root, { recursive: true, force: true }));
  writeFileSync(join(root, 'repository-manifest.json'), '{"customerOwned":true}');
  const install = args => spawnSync(shell, ['-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', installer, '-Scope', 'Project', '-ProjectPath', root, ...args], { encoding: 'utf8', timeout: 90000 });
  const first = install([]);
  assert.equal(first.status, 0, first.stderr + first.stdout);
  const receipt = JSON.parse(readFileSync(join(root, '.agents/buyna/sop-installation.json'), 'utf8'));
  assert.ok(existsSync(join(root, '.agents/buyna/sop', receipt.digest, 'manifest.json')));
  assert.equal(JSON.parse(readFileSync(join(root, 'repository-manifest.json'), 'utf8')).customerOwned, true);
  const taskPath = join(root, 'task.json');
  writeFileSync(taskPath, JSON.stringify({ projectId: 'installed', objective: 'repair', sopIds: ['change-and-maintenance'] }));
  const script = join(root, '.agents/skills/buyna-website-builder/scripts/project-agent-guide.mjs');
  const generated = spawnSync(process.execPath, [script, '--project-root', root, '--task', taskPath], { encoding: 'utf8' });
  assert.equal(generated.status, 0, generated.stderr);
  assert.match(readFileSync(join(root, 'AGENTS.md'), 'utf8'), new RegExp(receipt.digest));
  const originalGuide = readFileSync(join(root, 'AGENTS.md'), 'utf8');
  const second = install(['-Force', '-SkillsOnly']);
  assert.equal(second.status, 0, second.stderr);
  assert.equal(readFileSync(join(root, 'AGENTS.md'), 'utf8'), originalGuide);
  assert.ok(existsSync(join(root, 'packages/buyna-workflow-state-core/package.json')));
});
