import test from 'node:test';import assert from 'node:assert/strict';
import {assessResourceEvidence,createResourceEvidenceReceipt,decideHumanEscalation} from '../src/index.mjs';
const shared={instanceId:'i-shared',databaseInstanceIdentifier:'shared-rds',databaseName:'buyna_merchants',databaseConnectionSource:'SHOP_DATABASE_URL',storageProvider:'s3',storageIdentifier:'shared-bucket',region:'ap-northeast-1'};
const projectOwned={schema:'shop_a',runtimeIdentity:'shop-a.socket',environmentSource:'SHOP_A_DATABASE_URL',storagePrefix:'projects/shop_a/sellers/shop_a/'};
const sources={aws:'aws-readonly-20260818',runtime:'ssm-readonly-20260818',dns:'route53-readonly-20260818'};
test('candidate confirms shared resources without pretending project resources exist',()=>{const receipt=createResourceEvidenceReceipt({projectId:'shop_a',sellerId:'shop_a',architectureType:'shared_ec2_postgresql',shared,projectOwned,sources,expiresAt:'2026-08-19T00:00:00Z'});assert.equal(assessResourceEvidence({receipt,now:'2026-08-18T00:00:00Z'}).code,'SHARED_FOUNDATION_CONFIRMED');assert.equal(receipt.projectOwned.schema.status,'candidate')});
test('does not escalate before all automatic inspections are attempted',()=>{assert.deepEqual(decideHumanEscalation({attempts:[{kind:'aws',status:'pass'}]}).escalate,false);assert.equal(decideHumanEscalation({attempts:[{kind:'aws',status:'pass'}]}).code,'AUTOMATIC_INSPECTION_REQUIRED')});
test('escalates only after attempted inspection fails',()=>{const result=decideHumanEscalation({attempts:[{kind:'aws',status:'pass'},{kind:'runtime',status:'unavailable'},{kind:'dns',status:'pass'}]});assert.equal(result.escalate,true);assert.deepEqual(result.missing,['runtime'])});
test('rejects placeholders and expired evidence',()=>{assert.throws(()=>createResourceEvidenceReceipt({projectId:'shop_a',sellerId:'shop_a',architectureType:'shared_ec2_postgresql',shared:{...shared,instanceId:'unknown'},projectOwned,sources,expiresAt:'2026-08-19T00:00:00Z'}),/SHARED_INSTANCEID_REQUIRED/);const receipt=createResourceEvidenceReceipt({projectId:'shop_a',sellerId:'shop_a',architectureType:'shared_ec2_postgresql',shared,projectOwned,sources,expiresAt:'2026-08-18T00:00:00Z'});assert.equal(assessResourceEvidence({receipt,now:'2026-08-19T00:00:00Z'}).status,'blocked')});
