/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubscriptionReturnRouteImport } from './routes/subscription.return'
import { Route as SubscribePlanRouteImport } from './routes/subscribe.$plan'
import { Route as PaymentSuccessRouteImport } from './routes/payment.success'
import { Route as ApiAiShoppingGuideRouteImport } from './routes/api/ai-shopping-guide'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as ApiPublicGlobepayRecurringNotifyRouteImport } from './routes/api/public/globepay-recurring-notify'
import { Route as AuthenticatedMerchantSubscriptionRouteImport } from './routes/_authenticated.merchant.subscription'
import { Route as AuthenticatedMerchantOrdersRouteImport } from './routes/_authenticated.merchant.orders'
import { Route as AuthenticatedBillingCardBoundRouteImport } from './routes/_authenticated.billing.card-bound'
import { Route as AuthenticatedAdminSubscriptionsRouteImport } from './routes/_authenticated.admin.subscriptions'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated.admin.settings'
import { Route as AuthenticatedAdminRecurringRouteImport } from './routes/_authenticated.admin.recurring'
import { Route as AuthenticatedAdminProjectsRouteImport } from './routes/_authenticated.admin.projects'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated.admin.payments'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated.admin.orders'
import { Route as AuthenticatedAdminCustomersRouteImport } from './routes/_authenticated.admin.customers'
import { Route as ApiPublicGlobepayNotifyRouteImport } from './routes/api/public/globepay.notify'
import { Route as AuthenticatedAdminSubscriptionsIdRouteImport } from './routes/_authenticated.admin.subscriptions.$id'
import { Route as AuthenticatedAdminCustomersIdRouteImport } from './routes/_authenticated.admin.customers.$id'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionReturnRoute = SubscriptionReturnRouteImport.update({
  id: '/subscription/return',
  path: '/subscription/return',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribePlanRoute = SubscribePlanRouteImport.update({
  id: '/subscribe/$plan',
  path: '/subscribe/$plan',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment/success',
  path: '/payment/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiShoppingGuideRoute = ApiAiShoppingGuideRouteImport.update({
  id: '/api/ai-shopping-guide',
  path: '/api/ai-shopping-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicGlobepayRecurringNotifyRoute =
  ApiPublicGlobepayRecurringNotifyRouteImport.update({
    id: '/api/public/globepay-recurring-notify',
    path: '/api/public/globepay-recurring-notify',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedMerchantSubscriptionRoute =
  AuthenticatedMerchantSubscriptionRouteImport.update({
    id: '/merchant/subscription',
    path: '/merchant/subscription',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMerchantOrdersRoute =
  AuthenticatedMerchantOrdersRouteImport.update({
    id: '/merchant/orders',
    path: '/merchant/orders',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBillingCardBoundRoute =
  AuthenticatedBillingCardBoundRouteImport.update({
    id: '/billing/card-bound',
    path: '/billing/card-bound',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminSubscriptionsRoute =
  AuthenticatedAdminSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRecurringRoute =
  AuthenticatedAdminRecurringRouteImport.update({
    id: '/recurring',
    path: '/recurring',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProjectsRoute =
  AuthenticatedAdminProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCustomersRoute =
  AuthenticatedAdminCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicGlobepayNotifyRoute = ApiPublicGlobepayNotifyRouteImport.update({
  id: '/api/public/globepay/notify',
  path: '/api/public/globepay/notify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminSubscriptionsIdRoute =
  AuthenticatedAdminSubscriptionsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminSubscriptionsRoute,
  } as any)
const AuthenticatedAdminCustomersIdRoute =
  AuthenticatedAdminCustomersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminCustomersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/api/ai-shopping-guide': typeof ApiAiShoppingGuideRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/subscribe/$plan': typeof SubscribePlanRoute
  '/subscription/return': typeof SubscriptionReturnRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRouteWithChildren
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/admin/recurring': typeof AuthenticatedAdminRecurringRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRouteWithChildren
  '/billing/card-bound': typeof AuthenticatedBillingCardBoundRoute
  '/merchant/orders': typeof AuthenticatedMerchantOrdersRoute
  '/merchant/subscription': typeof AuthenticatedMerchantSubscriptionRoute
  '/api/public/globepay-recurring-notify': typeof ApiPublicGlobepayRecurringNotifyRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/customers/$id': typeof AuthenticatedAdminCustomersIdRoute
  '/admin/subscriptions/$id': typeof AuthenticatedAdminSubscriptionsIdRoute
  '/api/public/globepay/notify': typeof ApiPublicGlobepayNotifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/api/ai-shopping-guide': typeof ApiAiShoppingGuideRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/subscribe/$plan': typeof SubscribePlanRoute
  '/subscription/return': typeof SubscriptionReturnRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRouteWithChildren
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/admin/recurring': typeof AuthenticatedAdminRecurringRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRouteWithChildren
  '/billing/card-bound': typeof AuthenticatedBillingCardBoundRoute
  '/merchant/orders': typeof AuthenticatedMerchantOrdersRoute
  '/merchant/subscription': typeof AuthenticatedMerchantSubscriptionRoute
  '/api/public/globepay-recurring-notify': typeof ApiPublicGlobepayRecurringNotifyRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/customers/$id': typeof AuthenticatedAdminCustomersIdRoute
  '/admin/subscriptions/$id': typeof AuthenticatedAdminSubscriptionsIdRoute
  '/api/public/globepay/notify': typeof ApiPublicGlobepayNotifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/api/ai-shopping-guide': typeof ApiAiShoppingGuideRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/subscribe/$plan': typeof SubscribePlanRoute
  '/subscription/return': typeof SubscriptionReturnRoute
  '/_authenticated/admin/customers': typeof AuthenticatedAdminCustomersRouteWithChildren
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/_authenticated/admin/recurring': typeof AuthenticatedAdminRecurringRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRouteWithChildren
  '/_authenticated/billing/card-bound': typeof AuthenticatedBillingCardBoundRoute
  '/_authenticated/merchant/orders': typeof AuthenticatedMerchantOrdersRoute
  '/_authenticated/merchant/subscription': typeof AuthenticatedMerchantSubscriptionRoute
  '/api/public/globepay-recurring-notify': typeof ApiPublicGlobepayRecurringNotifyRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/customers/$id': typeof AuthenticatedAdminCustomersIdRoute
  '/_authenticated/admin/subscriptions/$id': typeof AuthenticatedAdminSubscriptionsIdRoute
  '/api/public/globepay/notify': typeof ApiPublicGlobepayNotifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pricing'
    | '/admin'
    | '/api/ai-shopping-guide'
    | '/payment/success'
    | '/subscribe/$plan'
    | '/subscription/return'
    | '/admin/customers'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/projects'
    | '/admin/recurring'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/billing/card-bound'
    | '/merchant/orders'
    | '/merchant/subscription'
    | '/api/public/globepay-recurring-notify'
    | '/admin/'
    | '/admin/customers/$id'
    | '/admin/subscriptions/$id'
    | '/api/public/globepay/notify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pricing'
    | '/api/ai-shopping-guide'
    | '/payment/success'
    | '/subscribe/$plan'
    | '/subscription/return'
    | '/admin/customers'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/projects'
    | '/admin/recurring'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/billing/card-bound'
    | '/merchant/orders'
    | '/merchant/subscription'
    | '/api/public/globepay-recurring-notify'
    | '/admin'
    | '/admin/customers/$id'
    | '/admin/subscriptions/$id'
    | '/api/public/globepay/notify'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/pricing'
    | '/_authenticated/admin'
    | '/api/ai-shopping-guide'
    | '/payment/success'
    | '/subscribe/$plan'
    | '/subscription/return'
    | '/_authenticated/admin/customers'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/projects'
    | '/_authenticated/admin/recurring'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/subscriptions'
    | '/_authenticated/billing/card-bound'
    | '/_authenticated/merchant/orders'
    | '/_authenticated/merchant/subscription'
    | '/api/public/globepay-recurring-notify'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/customers/$id'
    | '/_authenticated/admin/subscriptions/$id'
    | '/api/public/globepay/notify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  ApiAiShoppingGuideRoute: typeof ApiAiShoppingGuideRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  SubscribePlanRoute: typeof SubscribePlanRoute
  SubscriptionReturnRoute: typeof SubscriptionReturnRoute
  ApiPublicGlobepayRecurringNotifyRoute: typeof ApiPublicGlobepayRecurringNotifyRoute
  ApiPublicGlobepayNotifyRoute: typeof ApiPublicGlobepayNotifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription/return': {
      id: '/subscription/return'
      path: '/subscription/return'
      fullPath: '/subscription/return'
      preLoaderRoute: typeof SubscriptionReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe/$plan': {
      id: '/subscribe/$plan'
      path: '/subscribe/$plan'
      fullPath: '/subscribe/$plan'
      preLoaderRoute: typeof SubscribePlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/success': {
      id: '/payment/success'
      path: '/payment/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-shopping-guide': {
      id: '/api/ai-shopping-guide'
      path: '/api/ai-shopping-guide'
      fullPath: '/api/ai-shopping-guide'
      preLoaderRoute: typeof ApiAiShoppingGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/globepay-recurring-notify': {
      id: '/api/public/globepay-recurring-notify'
      path: '/api/public/globepay-recurring-notify'
      fullPath: '/api/public/globepay-recurring-notify'
      preLoaderRoute: typeof ApiPublicGlobepayRecurringNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/merchant/subscription': {
      id: '/_authenticated/merchant/subscription'
      path: '/merchant/subscription'
      fullPath: '/merchant/subscription'
      preLoaderRoute: typeof AuthenticatedMerchantSubscriptionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/merchant/orders': {
      id: '/_authenticated/merchant/orders'
      path: '/merchant/orders'
      fullPath: '/merchant/orders'
      preLoaderRoute: typeof AuthenticatedMerchantOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing/card-bound': {
      id: '/_authenticated/billing/card-bound'
      path: '/billing/card-bound'
      fullPath: '/billing/card-bound'
      preLoaderRoute: typeof AuthenticatedBillingCardBoundRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/subscriptions': {
      id: '/_authenticated/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AuthenticatedAdminSubscriptionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/recurring': {
      id: '/_authenticated/admin/recurring'
      path: '/recurring'
      fullPath: '/admin/recurring'
      preLoaderRoute: typeof AuthenticatedAdminRecurringRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/projects': {
      id: '/_authenticated/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AuthenticatedAdminProjectsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/customers': {
      id: '/_authenticated/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AuthenticatedAdminCustomersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/globepay/notify': {
      id: '/api/public/globepay/notify'
      path: '/api/public/globepay/notify'
      fullPath: '/api/public/globepay/notify'
      preLoaderRoute: typeof ApiPublicGlobepayNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/subscriptions/$id': {
      id: '/_authenticated/admin/subscriptions/$id'
      path: '/$id'
      fullPath: '/admin/subscriptions/$id'
      preLoaderRoute: typeof AuthenticatedAdminSubscriptionsIdRouteImport
      parentRoute: typeof AuthenticatedAdminSubscriptionsRoute
    }
    '/_authenticated/admin/customers/$id': {
      id: '/_authenticated/admin/customers/$id'
      path: '/$id'
      fullPath: '/admin/customers/$id'
      preLoaderRoute: typeof AuthenticatedAdminCustomersIdRouteImport
      parentRoute: typeof AuthenticatedAdminCustomersRoute
    }
  }
}

interface AuthenticatedAdminCustomersRouteChildren {
  AuthenticatedAdminCustomersIdRoute: typeof AuthenticatedAdminCustomersIdRoute
}

const AuthenticatedAdminCustomersRouteChildren: AuthenticatedAdminCustomersRouteChildren =
  {
    AuthenticatedAdminCustomersIdRoute: AuthenticatedAdminCustomersIdRoute,
  }

const AuthenticatedAdminCustomersRouteWithChildren =
  AuthenticatedAdminCustomersRoute._addFileChildren(
    AuthenticatedAdminCustomersRouteChildren,
  )

interface AuthenticatedAdminSubscriptionsRouteChildren {
  AuthenticatedAdminSubscriptionsIdRoute: typeof AuthenticatedAdminSubscriptionsIdRoute
}

const AuthenticatedAdminSubscriptionsRouteChildren: AuthenticatedAdminSubscriptionsRouteChildren =
  {
    AuthenticatedAdminSubscriptionsIdRoute:
      AuthenticatedAdminSubscriptionsIdRoute,
  }

const AuthenticatedAdminSubscriptionsRouteWithChildren =
  AuthenticatedAdminSubscriptionsRoute._addFileChildren(
    AuthenticatedAdminSubscriptionsRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCustomersRoute: typeof AuthenticatedAdminCustomersRouteWithChildren
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminProjectsRoute: typeof AuthenticatedAdminProjectsRoute
  AuthenticatedAdminRecurringRoute: typeof AuthenticatedAdminRecurringRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminSubscriptionsRoute: typeof AuthenticatedAdminSubscriptionsRouteWithChildren
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCustomersRoute:
    AuthenticatedAdminCustomersRouteWithChildren,
  AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRoute,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedAdminProjectsRoute: AuthenticatedAdminProjectsRoute,
  AuthenticatedAdminRecurringRoute: AuthenticatedAdminRecurringRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminSubscriptionsRoute:
    AuthenticatedAdminSubscriptionsRouteWithChildren,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedBillingCardBoundRoute: typeof AuthenticatedBillingCardBoundRoute
  AuthenticatedMerchantOrdersRoute: typeof AuthenticatedMerchantOrdersRoute
  AuthenticatedMerchantSubscriptionRoute: typeof AuthenticatedMerchantSubscriptionRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedBillingCardBoundRoute: AuthenticatedBillingCardBoundRoute,
  AuthenticatedMerchantOrdersRoute: AuthenticatedMerchantOrdersRoute,
  AuthenticatedMerchantSubscriptionRoute:
    AuthenticatedMerchantSubscriptionRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  ApiAiShoppingGuideRoute: ApiAiShoppingGuideRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  SubscribePlanRoute: SubscribePlanRoute,
  SubscriptionReturnRoute: SubscriptionReturnRoute,
  ApiPublicGlobepayRecurringNotifyRoute: ApiPublicGlobepayRecurringNotifyRoute,
  ApiPublicGlobepayNotifyRoute: ApiPublicGlobepayNotifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
